### ISSUE TITLE
glTF Geometry Loader: Fix comments in PR #95 

### ISSUE THREAD

**Issue by trungtle** [WebGLSamples/WebGL2Samples#112]
#95

**Comment by shrekshao** [comment]
### Obsolete:

> ### Main fix and improvement for geometry loader
> - [x] Fix bufferview offset bug: read index data as part of vertex attribute data S
> - [ ] Test loading models with hierarchy and fix potential bugs S
> - [x] Cache loaded array buffers S
> - [ ] Onload function should only be called for once ! **Serious** T
>   ### Format, code quality, performance tweaks
> - [ ] Get the type (e.g. `FLOAT`) from the accessor, https://github.com/KhronosGroup/glTF/blob/master/specification/README.md#reference-accessor
> - [ ] Make separate object (more hierarchy), access like this:
> 
> ```
> scene.positions.numberOfComponents
> scene.positions.byteStride
> scene.positions.byteOffset
> scene.normals./* ... */
> ```
> - [ ] Use `new GLTF.Scene();` as [Patrick's comment](https://github.com/WebGLSamples/WebGL2Samples/pull/95#discussion_r56191516)
> - [ ] function syntax, [see Patrick's comment](https://github.com/WebGLSamples/WebGL2Samples/pull/95#discussion_r56191854)
> - [ ] for loop optimization [see Patrick's comment](https://github.com/WebGLSamples/WebGL2Samples/pull/95#discussion_r56191993)
> - [ ] [see Patrick's comment](https://github.com/WebGLSamples/WebGL2Samples/pull/95#discussion_r56192353)
> - [ ] Detach `loadGltf*` functions from `window` [see Patrick's comment](https://github.com/WebGLSamples/WebGL2Samples/pull/95#discussion_r56192353)
> - [ ] Delete loading gl-matrix-min in gltf loader js file [see Patrick's comment](https://github.com/WebGLSamples/WebGL2Samples/pull/95#discussion_r56194669)
> - [ ] `loadJSON` implementation [see Patrick's comment](https://github.com/WebGLSamples/WebGL2Samples/pull/95#discussion_r56194967)

**Comment by pjcozzi** [comment]
@shrekshao thanks for organizing this roadmap.  Let's address these issue in this repo, then we'll do the full glTF reference loader in a new repo.

**Comment by shrekshao** [comment]
@trungtle I fix buffer offset and delete the buffer type assumption. Still need to fix hierachy. You can fix buffer cache and other improvements based on [tle/gltf_loader](https://github.com/WebGLSamples/WebGL2Samples/tree/tle/gltf_loader), I brought back the `gltf_load.html` for testing

**Comment by trungtle** [comment]
Thanks Shrek!

-Tr

**Comment by shrekshao** [comment]
Fix geometry loader by refractoring the glTF loader, including multiple hierarchy. Update to samples later

Latest changes of glTF loader is now in this branch: [tle/gltf_loader](https://github.com/WebGLSamples/WebGL2Samples/tree/tle/gltf_loader)
