### ISSUE TITLE
Outreach Plan

### ISSUE THREAD

**Issue by pjcozzi** [WebGLSamples/WebGL2Samples#115]
Time most of this with the release of WebGL 2 or when it is easier to enable in browsers...
- [ ] Twitter
- [ ] Email to webgl-dev-list@googlegroups.com
- [ ] WebGL LinkedIn group
- [ ] Khronos news
- [ ] Include on WebGL wiki - https://www.khronos.org/webgl/wiki/Main_Page
- [ ] WebGL subreddit - https://www.reddit.com/r/webgl/ 
- [x] NYC WebGL meetup - https://twitter.com/thsherif/status/710785800632471556
- [x] WebGL + glTF BOF at SIGGRAPH - even if just quickly mentioned
- [x] WebGL + glTF BOF during GDC 2016
- [x] Include on RTR - http://www.realtimerendering.com/webgl.html
- [x] Zhihu 知乎, The counterpart of Quora in China - https://www.zhihu.com/question/41447132/answer/91977788?from=profile_answer_card

**Comment by pjcozzi** [comment]
Great community response to this project, once again amazing job @trungtle and @shrekshao, and congrats on graduating this semester!

**Comment by kenrussell** [comment]
+1, thank you @trungtle and @shrekshao for your great and timely work on this project, and congratulations on your graduations! Also thanks @pjcozzi for your leadership initiating this and all of your other student projects!

**Comment by shrekshao** [comment]
@pjcozzi @kenrussell Thanks for providing this awesome opensource project opportunity. We are now members of the WebGL community.

**Comment by trungtle** [comment]
@pjcozzi @kenrussell Thank you for your kind words. Very glad it has been helpful for the community.
