### ISSUE TITLE
Retest in time for SIGGRAPH

### ISSUE THREAD

**Issue by pjcozzi** [WebGLSamples/WebGL2Samples#128]
@trungtle @shrekshao would it be possible for you guys to retest all the examples on the latest developer browsers before SIGGRAPH and update the table in the README.md

**Comment by pjcozzi** [comment]
Also, SIGGRAPH is the week after next.

**Comment by shrekshao** [comment]
Sure. I'll take care of that

**Comment by trungtle** [comment]
I'll do the same for OSX test! Also, we'll see you guys at SIGGRAPH.

**Comment by pjcozzi** [comment]
Very nice, thanks @shrekshao @trungtle!

**Comment by kenrussell** [comment]
Note:
http://webglsamples.org/WebGL2Samples/#draw_image_space seems to have a bug in the shader. Could you look into this at the same time? Thanks.

The samples are looking good! They all run well on Chrome Canary on my MacBook Pro Retina.

**Comment by shrekshao** [comment]
No problem. We will take care of that!
Thanks.

**Comment by trungtle** [comment]
Retested all OSX samples.

I have updated compatibilities accordingly in the chart. On the Chrome
side, only etc compression sample doesn't seem to work, error with using
gl.compressedTexImage2D with invalid enum. I'll investigate further.

**Comment by pjcozzi** [comment]
@trungtle thanks for testing promptly.

@kenrussell @toji @zhenyao really impressive work getting your WebGL 2.0 implementation into such good shape!

**Comment by kenrussell** [comment]
@pjcozzi @trungtle @shrekshao thanks for your excellent work on this samples pack! It will be a valuable resource for developers.

Thanks for retesting. Could you please file a bug about the fbo_rtt_texture_array sample crashing on https://bugs.chromium.org/p/angleproject/issues/list ? Please send me the bug ID once done. Thanks.

The texture_etc2_eac failure on Mac OS X should be fixed soon; the ETC/EAC decompression code was just added on that platform. @vonture @zhenyao

**Comment by shrekshao** [comment]
Hi Ken

Sure. I think I can do that tomorrow evening.

Thanks for your help and suggestions through out the process. I do feel I
learn a lot from working with you. I will continue to keep an eye on this
repo for any updates and fixes. (At least I should be able to do a uniform
buffer sample making more sense since the driver issue of my machine should
be fixed)

Shrek

**Comment by shrekshao** [comment]
@kenrussell 
Issue 1451
https://bugs.chromium.org/p/angleproject/issues/detail?id=1451

**Comment by kenrussell** [comment]
Thanks. Commented on the bug and CC'd a couple of others.
