### ISSUE TITLE
UBO issue

### ISSUE THREAD

**Issue by shrekshao** [WebGLSamples/WebGL2Samples#14]
When I trying to implement UBO, things don't turn out quite as expected. 
- I think the browser support is no problem, since I got ubo working correctly in [draw_instance_ubo](https://github.com/WebGLSamples/WebGL2Samples/blob/dev-instance-ubo/samples/draw_instanced.html)
- Yet with almost the same code (simply copying and delete one of the two ubo), in [draw_range_arrays](https://github.com/WebGLSamples/WebGL2Samples/blob/dev-shrek-draw-range-arrays/samples/draw_range_arrays.html) when I use the transform.MVP (identiy matrix), the polygons just go away, no error is reported. 
- My first UBO try can be found here [buffer_uniform](https://github.com/WebGLSamples/WebGL2Samples/blob/dev-shrek-buffer-uniform/samples/buffer_uniform.html), which is a direct port from Christ's ogl sample and is quite complex comparing to the last two. There's an error 1282 (GL_INVALID_OPERATION) at the draw calls. Since this is more complex, I just paused this and let's focus the first two for debugging first and later turn to this one. 

So I'd like to learn if there's some good way to test the ubo.

**Comment by shrekshao** [comment]
[draw_instance_ubo](https://github.com/WebGLSamples/WebGL2Samples/blob/dev-instance-ubo/samples/draw_instanced_ubo.html)

This sample works fine in Chrome 47, but reported errors in Chrome Canary 49

```
WebGL: INVALID_OPERATION: useProgram: program not valid
```

**Comment by kenrussell** [comment]
I'll look into this failure.

**Comment by shrekshao** [comment]
Revisit:
* Our samples seem to get rid of the "draw half of the rect sometimes" bug
*  the conformance test still failed on several tests ( but much fewer, focus on lowp and mediump now)

**Comment by pjcozzi** [comment]
Does README.md need to be updated?

**Comment by shrekshao** [comment]
Oh sorry, this is a mistake. I should reopen this one

**Comment by shrekshao** [comment]
- Canary on windows still fails most of the uniformbuffers test: https://www.khronos.org/registry/webgl/sdk/tests/deqp/functional/gles3/uniformbuffers.html?webglVersion=2&quiet=0
- But one of our simple sample using UBO can now successfully run: [draw_instance_ubo](https://github.com/WebGLSamples/WebGL2Samples/blob/dev-instance-ubo/samples/draw_instanced_ubo.html)

@pjcozzi So are we going to bring UBO in the samples pack before GDC? I guess so.

**Comment by shrekshao** [comment]
@trungtle Can you help take a look at these two samples when you are free:
- https://github.com/WebGLSamples/WebGL2Samples/blob/dev-shrek-buffer-uniform/samples/buffer_uniform.html
- https://github.com/WebGLSamples/WebGL2Samples/blob/dev-shrek-buffer-uniform/samples/draw_instanced_ubo.html

The second is now working, the first uses almost the same uniform buffer but when multiplying the matrix from the uniform block seems that the data hasn't loaded correclty. I really don't get it ...

**Comment by trungtle** [comment]
I tested both on my machine, looks good to me actually. What did you mean by the data hasn't loaded correctly?

<img width="624" alt="screen shot 2016-03-07 at 10 41 49 am" src="https://cloud.githubusercontent.com/assets/486501/13579249/42f7f0da-e451-11e5-82d7-b45c1fa7bcdc.png">
<img width="1048" alt="screen shot 2016-03-07 at 10 41 54 am" src="https://cloud.githubusercontent.com/assets/486501/13579250/42fc7d1c-e451-11e5-998c-67499683d173.png">

**Comment by shrekshao** [comment]
So it works correctly on Mac. 
For the first one, the canvas is blank on Windows chrome canary 51. I think the problem might be the uniform buffer object transferring. 
It's weird that the second one works well on Windows.
Trung and I will clean the code and @kenrussell you might take a look at this [sample](https://github.com/WebGLSamples/WebGL2Samples/blob/dev-shrek-buffer-uniform/samples/buffer_uniform.html)

**Comment by kenrussell** [comment]
@shrekshao Please file a bug on crbug.com/ with clear reproduction steps and email me the bug ID. Thanks.

**Comment by shrekshao** [comment]
@kenrussell 
Issue 593024: https://bugs.chromium.org/p/chromium/issues/detail?id=593024

**Comment by shrekshao** [comment]
So according to: [Issue 593024](https://bugs.chromium.org/p/chromium/issues/detail?id=593024&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=)
It seems like something specific with my laptop. 
@trungtle Can you take over this sample? The full version cleaned code is [here](https://github.com/WebGLSamples/WebGL2Samples/blob/dev-shrek-buffer-uniform/samples/buffer_uniform.html) Need further test. 
I think the UBO is able to be merged before GDC.

**Comment by pjcozzi** [comment]
@trungtle any update here?  It would be nice to merge the UBO sample today if we are sure this is just an issue with @shrekshao's machine.

**Comment by trungtle** [comment]
There is still an issue with one of the two samples. I think we could merge the working UBO sample first.

**Comment by shrekshao** [comment]
@kenrussell Hi Ken. How is Uniform buffer going for windows? I saw canary have 100% passed the webgl 2 conformance test. And I revisit the uniform buffer example (now merged to master) and find the data transferring is still not working as expected (on Windows). Since it might be the issue of my machine mind @trungtle mind giving a test on Mac when you got time?

**Comment by kenrussell** [comment]
I'm pretty sure uniform buffers should be working well at this point -- I'd be surprised if they are not tested by the conformance suite. Have you double-checked your work? Have you tested on Firefox? CC'ing @null77 and @vonture who work on ANGLE.

**Comment by null77** [comment]
I believe UBOs have bugs on Intel drivers. Other than that, no known issues.

**Comment by shrekshao** [comment]
i would use the mac at my work place to test again. Hope it is some minor
problem in my sample.

**Comment by shrekshao** [comment]
Seems like the issue of Intel driver (My PC has an integrated Intel graphics driver). I can get the uniform buffer data transferred correctly to the device on a Mac. I will finish this sample ASAP

**Comment by shrekshao** [comment]
Fixed in commit f5028ed2410e2c52db370ffa6a4d7d5b9f48f2ec
