### ISSUE TITLE
[qu] draw_instanced.html question

### ISSUE THREAD

**Issue by quantuminformation** [WebGLSamples/WebGL2Samples#141]
Thanks, I'm trying to understand why do you need to call

        `gl.bindVertexArray(vertexArray);`

twice? I see that if you don't do the initial call you get a black screen.

**Comment by shrekshao** [comment]
Hi Nikos,
Cuz we do a 

    gl.bindVertexArray(null);

at https://github.com/WebGLSamples/WebGL2Samples/blob/master/samples/draw_instanced.html#L90, indicating we finish defining a vertex array.

You can comment this line and the second `gl.bindVertexArray(vertexArray);` together to get the sample still working

**Comment by quantuminformation** [comment]
Thanks for this!
