### ISSUE TITLE
I dont know what any of these samples mean

### ISSUE THREAD

**Issue by Meai1** [WebGLSamples/WebGL2Samples#152]
I'm just not proficient enough about OpenGL to know what all this stuff is helping me with. 
Can you add more explanations of where I would want to use these techniques, and how this improves on the old way of doing things and what that old way was?

**Comment by shrekshao** [comment]
Basically every sample in this repo demonstrates a new single feature in WebGL 2 (doesn't exist in WebGL 1 at all). If you would like to see what kind of higher level feature can be implemented with these newly introduced functionality, Tarek's [WebGL 2 Examples](https://github.com/tsherif/webgl2examples) can be a good resource where things like particles, screen space ambient occulsion, deferred shading are implemented in webgl 2 fashion.

**Comment by tsherif** [comment]
I'd probably start with [Gregg Tavares' WebGL 2 Fundamentals](https://webgl2fundamentals.org/) if you're not that comfortable with 3D yet. Most of the new WebGL 2 features target more advanced rendering techniques and optimizations that you won't get much out of until you've got a solid foundation in the basics.
