### ISSUE TITLE
draw image space example

### ISSUE THREAD

**Issue by itsyom** [WebGLSamples/WebGL2Samples#158]
In the draw image space example 
in fragment shader:
color = texture(diffuse, vec2(gl_FragCoord.x,1.0 - gl_FragCoord.y) / u_imageSize);
shoule replace 1.0 by u_imageSize.y.
Am I right?

**Comment by shrekshao** [comment]
Yeah I think you are correct. Would you mind opening a pull request for this? I'd be happy to merge it in

**Comment by shrekshao** [comment]
NVM, I've fixed this issue. Thank you!

**Comment by itsyom** [comment]
Thank you!
