### ISSUE TITLE
instanceRotations is not used...

### ISSUE THREAD

**Issue by AaronWatters** [WebGLSamples/WebGL2Samples#162]
I think you mean to use`instanceRotations` here in place of `instanceOffsets`.

https://github.com/WebGLSamples/WebGL2Samples/blob/master/samples/transform_feedback_instanced.html#L233

**Comment by shrekshao** [comment]
Thanks for pointing this out. Yes I think this is a typo.

**Comment by shrekshao** [comment]
Fixed in #163
