### ISSUE TITLE
WebGL2 Browser experiment setup

### ISSUE THREAD

**Issue by shrekshao** [WebGLSamples/WebGL2Samples#2]
The webgl-2 experiment setup goes like this ~~(I've tested on Windows only)~~ (tested on Windows and OSX 10.10.5).
The [Mozilla Wiki WebGL2 Link](https://wiki.mozilla.org/Platform/GFX/WebGL2) seems to miss one config flag in my case. So I post my methods here FYI. 
- FireFox:
  set the following config flags value to _true_ in `about:config`
  `webgl.disable-angle`
  `webgl.enable-prototype-webgl2`
  `webgl.force-enabled`
- Chrome:
  launch chrome through command line with an additional flag
  
  > .\chrome.exe --enable-unsafe-es3-apis

[How to Get WebGL 2 implementation](https://www.khronos.org/webgl/wiki/Getting_a_WebGL_Implementation)

**Comment by trungtle** [comment]
@shrekshao tested on Chrome. Same settings.

**Comment by pjcozzi** [comment]
For reference, on Windows 10, the full command for running Canary with WebGL 2 is:

```
"C:\Users\[user]\AppData\Local\Google\Chrome SxS\Application\chrome.exe" --enable-unsafe-es3-apis
```

**Comment by pjcozzi** [comment]
Here is the latest on WebGL 2 in Firefox Nightly: http://muizelaar.blogspot.com/2015/12/webgl2-enabled-in-firefox-nightly.html

**Comment by ghost** [comment]
WebGL2 in Chrome Canary (Windows) no longer works for me. Anyone else experiences this issue?

**Comment by trungtle** [comment]
@lambdor still works for me. Did you launch with " ./chrome.exe --enable-unsafe-es3-apis" ?

**Comment by ghost** [comment]
Yes. It actually worked two weeks ago and suddenly stopped with an auto update. Using Windows x64 + Chrome 51.0.2692.0 canary (64-bit), started with `--enable-unsafe-es3-apis` and enabled "WebGL 2.0 Prototype" and "WebGL Draft Extensions" in `about:flags`. Anyway, I just wanted to drop this in case someone else experiences this issue. WebGL2 still works for me in Firefox.

**Comment by kenrussell** [comment]
@lambdor 64-bit Chrome canary (actually, a continuous Chromium build from http://build.chromium.org -- see http://crbug.com/598407 ) is working OK on my Windows 8.1 workstation. Contents of about:gpu shown at http://pastebin.com/rT4RDkR0 . I do note that http://toji.github.io/webgl2-particles-2/ seems slow; will try to investigate why.

Can you try again with just the command line flag:
  --user-data-dir=C:\Users[your username]\tmp\t1

(making sure that "tmp" exists and there's currently no "t1" directory)

and copy/paste the contents of about:gpu somewhere?

Then can you relaunch with --enable-unsafe-es3-apis ? Does about:gpu still work? Can you post that too?
