### ISSUE TITLE
ERROR: 0:7: 'gl_VertexID' : undeclared identifier

### ISSUE THREAD

**Issue by shrekshao** [WebGLSamples/WebGL2Samples#39]
gl_VertexID should be a builtin input for the vertex shader as long as calling a draw call without using GL_ELEMENT_ARRAY_BUFFER, https://www.khronos.org/opengles/sdk/docs/man3/html/gl_VertexID.xhtml

But I get `ERROR: 0:7: 'gl_VertexID' : undeclared identifier` when using `gl_VertexID` in 27e326c26e696fb48b9287d274c39593c58f49f0

Same error when using Firefox, so I think it might be something wrong with my program

@pjcozzi @kenrussell ask for help....

**Comment by pjcozzi** [comment]
It looks OK at a glance.  Did you review the conformance test?

https://github.com/KhronosGroup/WebGL/blob/fadaa8364df1ca1db8bc5c1376c030fd9a9d211e/sdk/tests/deqp/functional/gles3/es3fShaderBuiltinVarTests.js#L732

Does this test pass for you?  In general, it is probably worth your while to step through a particular conformance test in the debugger if it works and your code does not.

**Comment by shrekshao** [comment]
I run this test and get: `failed: builtin_variable.vertex_id: Compile failed`

So does this mean that currently implementation for `vertex_id` is still unavailable here? 

Fortunately we can still use another version without `vertex_id` for this sample `draw_image_space`. 

Thanks for this note. Next time I will run the conformance test first.

**Comment by pjcozzi** [comment]
Yes, sounds like this is a browser issue.

**Comment by kenrussell** [comment]
Thanks for pointing this out and sorry for the trouble. Filed as http://crbug.com/575073 .

**Comment by pjcozzi** [comment]
Thanks for submitting the issue, @kenrussell!  We have plenty to work on in the meantime!

**Comment by shrekshao** [comment]
`gl_VertexID` still fails the conformance test.

**Comment by kenrussell** [comment]
@shrekshao gl_VertexID is still being implemented in ANGLE and Chrome.

**Comment by ghost** [comment]
[http://stackoverflow.com/a/11659693/392549](SO - in int gl_VertexID causing error with three.js)

> As far as I'm aware, in WebGL you can't access built-in vertex indices.
> However you should be able emulate this by providing your own custom attribute stream, set to values that would be equivalent to such built-in index stream.

**Comment by shrekshao** [comment]
@lambdor I think the point is gl_VertexID is not in WebGL 1. But there will be support in WebGL 2

**Comment by kenrussell** [comment]
Correct @shrekshao . gl_VertexID will be implemented in http://crbug.com/587781 .

**Comment by ghost** [comment]
What is the point of the sample and does it have to rely on gl_VertexID?

**Comment by shrekshao** [comment]
@lambdor Basically it's just showing how to use `gl_VertexID` in the shader. 
It is correct as you've mentioned that providing an extra index attribute for each vertex can do the same thing. Unfortunately I'm not very familiar with `gl_VertexID` acutal usage in real application. It may give you some knowledge of vertex adjacency as stated here: http://gamedev.stackexchange.com/questions/74249/gl-vertexid-values-when-calling-gldrawelements
