### ISSUE TITLE
TransformFeedback doesn't work for Google Chrome Canary anymore

### ISSUE THREAD

**Issue by shrekshao** [WebGLSamples/WebGL2Samples#48]
Might be trigged by an auto update. Still works for Firefox

```
WebGL: INVALID_OPERATION: endTransformFeedback: transform feedback is not active
```

**Comment by pjcozzi** [comment]
Also, see if the related tests in the conformance suite fail in case we are doing something wrong in the sample.  The sample looks simple enough to me: https://github.com/WebGLSamples/WebGL2Samples/blob/af9ab5bdc2fa6836a9a095ddf6d525ebd9f43178/samples/transform_feedback_interleaved.html#L212-L214

**Comment by kenrussell** [comment]
Was an error generated during beginTransformFeedback?

http://toji.github.io/webgl2-particles-2/ is working for me -- it uses transform feedback in a reasonably sophisticated way. @toji

**Comment by kenrussell** [comment]
(Unfortunately, NVIDIA's driver fails some of the cases in sdk/tests/deqp/functional/gles3/transformfeedback.html , and I haven't implemented a skip list for the dEQP tests yet, so that test isn't turned on on our automated test bots.)

**Comment by kenrussell** [comment]
BTW, that's on Mac OS X with Chrome Canary.

**Comment by shrekshao** [comment]
The error is generated at `endTransformFeedback` saying `transform feedback is not active`. So yes, it may be because the failure of `beginTransformFeedback`

Good suggestion, I will look at toji's code for a more complete calling of transform feedback.
