### ISSUE TITLE
Set up JSHint to run on all examples

### ISSUE THREAD

**Issue by pjcozzi** [WebGLSamples/WebGL2Samples#5]
http://jshint.com/

We need to look into it, but this may require separating the JavaScript into .js files (or doing that on-the-fly for JSHint).

**Comment by mramato** [comment]
JSHint automatically extracts JavaScript from HTML files, there's nothing special you have to do on your end. I would recommend using Node and Gulp like we do in Cesium and it should only be about 10 lines of JavaScript for the whole thing, you can even copy/paste the Cesium code: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/gulpfile.js#L201
