### ISSUE TITLE
Code consistency improvements

### ISSUE THREAD

**Issue by pjcozzi** [WebGLSamples/WebGL2Samples#51]
- [x] Use `v_` for GLSL varyings (some examples do, some don't)
- [x] Consistently always use a constant or a literal for layout locations, e.g., currently some examples use `layout(location = 0) in vec2 position;` and others us `layout(location = POSITION) in vec2 position;`.
- [x] Change

``` javascript
if(!isWebGL2)
{
```

to

``` javascript
if(!isWebGL2) {
```

**Comment by shrekshao** [comment]
Do you refer to the output of a vertex shader when saying 'varyings'?

**Comment by pjcozzi** [comment]
Yes, varyings are `out` in the vertex shader and `in` in the fragment shader.
