### ISSUE TITLE
Descriptions for each sample

### ISSUE THREAD

**Issue by pjcozzi** [WebGLSamples/WebGL2Samples#52]
From the name alone, it's not always clear what the output for a sample is supposed to be or even exactly what WebGL 2 feature the sample is demonstrating.  Let's provide a short description (screenshot, tooltip, etc.) for each.  We'll have to figure out the form factor.

**Comment by pjcozzi** [comment]
@shrekshao what is the latest here?  Do all samples have a description now when they are loaded?

I'm not sure how hard it would be, but it would be really useful to show the same string as a mouse-over tooltip for each sample in the list of samples.

**Comment by trungtle** [comment]
We're only missing draw_range_array and draw_image_space descriptions.

**Comment by pjcozzi** [comment]
Perhaps we update them before GDC and then wait on the tooltips until after?
