### ISSUE TITLE
Notes for ETC2/EAC sample

### ISSUE THREAD

**Issue by shrekshao** [WebGLSamples/WebGL2Samples#60]
- etc2/eac compressed image can be in different file extension (ktx, pkm), each has a different "header data". For example, ktx file format has a header data of 68 bytes [details](https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/#4). 
- To properly handle this, we may need a so-called "texture utils". Extract the data correctly from images in different format, which can be another project. 
- In this sample, I hard-coded an offset of 68 to drag the image data from the arraybuffer. Improvement can be made later.

**Comment by pjcozzi** [comment]
There is now code in Cesium to parse KTXs: https://github.com/AnalyticalGraphicsInc/cesium/pull/4758

**Comment by shrekshao** [comment]
Hmm, that is for ECT1. But I will certainly try to look into this one. It once worked on Chrome. Probably because it was some sketchy implementation at that time.

**Comment by kainino0x** [comment]
ETC2/EAC were moved into an extension shortly before the release of WebGL 2, as it has terrible performance characteristics on platforms where it's not actually supported by the hardware.

KhronosGroup/WebGL#2030

**Comment by shrekshao** [comment]
@kainino0x  Thanks Kai for the clarifications. I will remove this sample from the list and leave a link to https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_etc/ in the future

**Comment by kainino0x** [comment]
Sorry, that link is outdated because the extension got renamed. Here's the correct link:

https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_etc/
