### ISSUE TITLE
Use gl-matrix-min.js of version 2

### ISSUE THREAD

**Issue by shrekshao** [WebGLSamples/WebGL2Samples#65]
Use gl-matrix-min.js 2.0. The gl-matrix.js in repo at present is version 1.x. Since there's a issue with the texture-3d sample using the new 2.0 gl-matrix, I will remain the old version gl-matrix there and come back later to fix that.

**Comment by shrekshao** [comment]
Since we are using gl-matrix 2 in gltf-loader, now we must change old version gl-matrix api uses to make the gltf loader work. I have fixed one in #84 which can be referenced. As far as I know there's a `texture_vertex` which at the same time uses gltf-loader, and `texture_3d`. @trungtle can you take care of these two when you get time?

**Comment by trungtle** [comment]
Will do. Thanks for taking care of it.

-Tr

**Comment by toji** [comment]
What's the issue with glMatrix in the texture-3d sample? I'm happy to fix anything that's blocking you.

**Comment by shrekshao** [comment]
Oh hi Brandon, sorry about making things confused. It's not about the gl-matrix it self. It's just because we happened to use version 1.2.3 in some previous samples and some in version 2. We want to use version 2 in all samples to make it consistent.

**Comment by pjcozzi** [comment]
@shrekshao @trungtle is the plan to move to version 2 before or after GDC?

**Comment by shrekshao** [comment]
Before. It won't take long.

**Comment by pjcozzi** [comment]
:+1:

**Comment by pjcozzi** [comment]
@shrekshao did you mean to close this?

**Comment by shrekshao** [comment]
Trung has done it in #98

**Comment by pjcozzi** [comment]
Ah, but why didn't we remove the old file: https://github.com/WebGLSamples/WebGL2Samples/blob/master/samples/third-party/gl-matrix.js
