### ISSUE TITLE
Update table from Chrome 49 to 50.

### ISSUE THREAD

**Issue by pjcozzi** [WebGLSamples/WebGL2Samples#66]
And, of course, retest each sample.

**Comment by pjcozzi** [comment]
Reopening this to test Chrome 50 on Mac.

**Comment by trungtle** [comment]
Retested with Chrome 50 on OSX, 3 samples not working: draw_image_space (gl_vertexID not supported), texture_etc2_eac (I'm not sure why yet), fbo_multisample (webGL2 context lost)

**Comment by kenrussell** [comment]
I've made a note of these failures on http://crbug.com/575073 . We'll investigate soon.

**Comment by pjcozzi** [comment]
Thanks @kenrussell.

@trungtle in the meantime, can you open a PR to update our README.md?

**Comment by trungtle** [comment]
@pjcozzi I updated the READ.md file for the Chrome on OSX issues I mentioned above. If we need to include more details I can open a new PR for it.

**Comment by pjcozzi** [comment]
Thanks!
