### ISSUE TITLE
gl.POINTS not rendered on OSX 10.10.5 with Chrome Canary 50 nor Firefox 45

### ISSUE THREAD

**Issue by trungtle** [WebGLSamples/WebGL2Samples#71]
Checkout `tle/test_glpoint`. The sample name is test_sample_glpoint. There is a commented out draw call for gl.TRIANGLES for comparison. Could be related to [this](https://code.google.com/p/chromium/issues/detail?id=558738)?

**Comment by pjcozzi** [comment]
I can confirm this works on Windows so it is likely Mac specific.  Try `drawArrays` without an index buffer since using point primitives with indices is not a popular use case; it could be buggy.

**Comment by kenrussell** [comment]
Could this possibly be http://crbug.com/558738 ?

**Comment by trungtle** [comment]
Yes, I think it's a similar issue. I have linked the same ticket with the first comment

**Comment by trungtle** [comment]
close this, looks like it's working now.
