### ISSUE TITLE
Update Test result for new version browsers

### ISSUE THREAD

**Issue by shrekshao** [WebGLSamples/WebGL2Samples#72]
- [x] Chrome Canary 51 Win 10
- [x] Chrome Canary 51 Mac
- [x] Firefox Developer Edition 47 Win 10
- [x] Firefox Developer Edition 47 Mac

**Comment by shrekshao** [comment]
@trungtle we need to finish the test table before GDC

**Comment by pjcozzi** [comment]
@trungtle @shrekshao any update here?  Can we finish this today?

**Comment by shrekshao** [comment]
I don't have a mac. Patrick you may get it done with Trung

**Comment by trungtle** [comment]
I can get this done today. Sorry about this.

**Comment by trungtle** [comment]
Done tested on Mac
