### ISSUE TITLE
sample: primitive-restart problem

### ISSUE THREAD

**Issue by shrekshao** [WebGLSamples/WebGL2Samples#77]
- primitive restart fails the conformance test
- seems that it is the problem of TRIANGLES_STRIP. Even without the degenerate-triangle, the TRIANGLE_STRIP doesn't work
- try to test TRIANGLES_STRIP in webgl 1 context

**Comment by shrekshao** [comment]
PASS getError was expected value: INVALID_OPERATION : after evaluating: context.drawElements(context.TRIANGLE_STRIP, 4, context.UNSIGNED_SHORT, 0)

It is expected not to work in webgl2?

**Comment by kenrussell** [comment]
@shrekshao It sounds like a bug but please provide a small and self-contained test case. It would be ideal if you would file a bug on crbug.com/ and email me the bug ID.

**Comment by shrekshao** [comment]
@trungtle Could you help test this on Mac to see if it works? Simply copy and paste the content to a single html file and open it in canary will work. It is expected to draw a triangle. 
https://github.com/WebGLSamples/WebGL2Samples/blob/dev-shrek-primitive-restart/samples/draw_primitive_restart_triangle_strip_self_test.html

**Comment by kenrussell** [comment]
@shrekshao That sample produces a black canvas on both Mac OS and Windows for me. Retina MBP (NVIDIA), 51.0.2673.0 (Official Build) canary (64-bit); Windows 8.1 with AMD GPU, 51.0.2672.0 (Official Build) canary (64-bit).

**Comment by shrekshao** [comment]
@kenrussell Thanks. This is helpful.

**Comment by kenrussell** [comment]
@shrekshao You're welcome. Note that there may well still be bugs in all or most WebGL implementations around primitive restart. I'm not sure we've studied those conformance tests in Chrome yet.

**Comment by kenrussell** [comment]
There's a typo in the sample -- TRIANGLES_STRIP instead of TRIANGLE_STRIP.

**Comment by shrekshao** [comment]
-_-!!  This is stupid.... Fixed, thanks a lot ken!
So the TRIANGLE_STRIP itself is nothing wrong. 

The primitive restart feature is still not working. As it fails in the conformance test. Ken also points it out.  This sample will be pending.

**Comment by kenrussell** [comment]
Right. Primitive restart isn't supported correctly in Chromium's WebGL 2.0 implementation yet though. I found a few issues trying to get your sample to work and filed http://crbug.com/594021 about them. Thanks for helping uncover these problems.

**Comment by shrekshao** [comment]
It is now supported
