### ISSUE TITLE
OpenGL ES 3 Shading Language  new built in function comparing to ES 2

### ISSUE THREAD

**Issue by shrekshao** [WebGLSamples/WebGL2Samples#83]
- Angle & Trigonometry Functions
  T sinh (T x); hyperbolic sine
  T cosh (T x); hyperbolic cosine
  T tanh (T x); hyperbolic tangent
  T asinh (T x); arc hyperbolic sine; inverse of sinh
  T acosh (T x); arc hyperbolic cosine; non-negative inverse of cosh
  T atanh (T x); arc hyperbolic tangent; inverse of tanh
- Common Functions
  full integer/uint and integer/uint vector support
  TB isnan(T x); true if x is a NaN
  TB isinf(T x); true if x is positive or negative infinity
  TI floatBitsToInt(T value);
  TU floatBitsToUint(T value); highp integer, preserving float bit level representation
  T intBitsToFloat(TI value);
  T uintBitsToFloat(TU value);highp float, preserving integer bit level representation
- Floating-Point Pack and Unpack Functions
  uint packSnorm2x16(vec2 v);
  uint packUnorm2x16(vec2 v); convert two floats to fixed point and pack into an integer
  vec2 unpackSnorm2x16(uint p);
  vec2 unpackUnorm2x16(uint p); unpack fixed point value pair into floats
  uint packHalf2x16(vec2 v); convert two floats into half-precision floats and pack into an integer
  vec2 unpackHalf2x16(uint v); unpack half value pair into full floats
- Matrix Functions
  mat2 outerProduct(vec2 c, vec2 r);
  mat3 outerProduct(vec3 c, vec3 r);
  mat4 outerProduct(vec4 c, vec4 r); linear algebraic column vector \* row vector
  mat2x3 outerProduct(vec3 c, vec2 r);
  mat3x2 outerProduct(vec2 c, vec3 r);
  mat2x4 outerProduct(vec4 c, vec2 r);
  mat4x2 outerProduct(vec2 c, vec4 r);
  mat3x4 outerProduct(vec4 c, vec3 r);
  mat4x3 outerProduct(vec3 c, vec4 r); linear algebraic column vector \* row vector
  mat2 transpose(mat2 m);
  mat3 transpose(mat3 m);
  mat4 transpose(mat4 m);
  mat2x3 transpose(mat3x2 m);
  mat3x2 transpose(mat2x3 m);
  mat2x4 transpose(mat4x2 m);
  mat4x2 transpose(mat2x4 m);
  mat3x4 transpose(mat4x3 m);
  mat4x3 transpose(mat3x4 m); transpose of matrix m
  float determinant(mat2 m);
  float determinant(mat3 m);
  float determinant(mat4 m); determinant of matrix m
  mat2 inverse(mat2 m);
  mat3 inverse(mat3 m);
  mat4 inverse(mat4 m); inverse of matrix m
- Fragment Processing Functions  **_texture_derivative**_
  T dFdx(T p); Derivative in x  
  T dFdy(T p); Derivative in y
  T fwidth(T p); abs (dFdx (p)) + abs (dFdy (p));
- Texture Lookup Functions
  3D texture support, vertex/fragment shader support **_texture_2d_array**_, **_texture_3d**_
  textureOffset **_texture_offset**_
  texelFetch **_texture_fetch**_
  texelFetchOffset
  textureProjOffset
  textureGrad **_texture_grad**_
  textureProjGrad
  textureGradOffset
  textureProjGrad
  textureProjGradOffset

**Comment by pjcozzi** [comment]
For the GLSL sample(s), I also want to include the new language features such as non-uniform matrices (which I suppose is implicit above).

**Comment by shrekshao** [comment]
There are a lot of matrix functions related to non-square matrix. I think I just need to find a scenario to use these functions.
