### ISSUE TITLE
Replace "View source" link

### ISSUE THREAD

**Issue by pjcozzi** [WebGLSamples/WebGL2Samples#92]
Instead of opening up the page's source, it could be more instructive to open a link to the page on GitHub, including the highlighted section of relevant code, e.g., https://github.com/WebGLSamples/WebGL2Samples/blob/master/samples/texture_2d_array.html#L143-L157

**Comment by shrekshao** [comment]
@trungtle Add highlightedLines lines tag at the end of each sample html as it is done here: 
https://github.com/WebGLSamples/WebGL2Samples/blob/master-view-source-link-change/samples/texture_2d_array.html#L198

#106
